### ISSUE TITLE
False Error: Quoted field not terminated at line 

### ISSUE THREAD

**Issue by jhihn** [adaltas/node-csv-parse#173] opened 2017-12-04 21:26 UTC
I work with some large CSV files. Unfortunately, I cannot share them. However, I was getting a false "Quoted field not terminated at line" error. The file itself was programmatically generated and used lazy quoting (only text fields with commas get quoted)
The file only has two fields, and the specific line was like:
,"sfd sdfs sd sdf sdf sdf sdf, sfd sdf sdf, sd fsdf sd f"
I tried many things, but I could only fix it by removing the " and the , from the line.
I verified there was not a row cascading.
Here's the weird thing, I was able to get shorter lines to work:
,"sfd sdfs sd" would work but when I added the next "'sdf" to the line it would fail, even though I was just inserting characters in the file. The editor was `nano` so I'm sure there was no hanky-panky.

**Comment by wdavidw** [comment] 2017-12-04 21:34
Could you please provide a sample reproducing the issue, thanks

**Comment by jhihn** [comment] 2017-12-05 14:32
Here's a test case and a sample.
In the csv there is only 1 B in the file at line 18376. If you remove the quotes at the field start and field end, and remove the commas (to keep it valid as a 2-field csv)  the error will go away.

[test_node_parse.zip](https://github.com/adaltas/node-csv-parse/files/1531470/test_node_parse.zip)

**Comment by wdavidw** [comment] 2017-12-11 12:00
I'm pretty sure this is related to you calling `csv.end()` on csv in the middle of parsing. Could you confirm?

**Comment by jhihn** [comment] 2017-12-11 16:13
Yes. Confirmed.

What is a proper way to abort reading the file? I have many requests scanning many files for just a few lines, and I want to save the disk i/o bandwidth.

**Comment by wdavidw** [comment] 2017-12-11 19:48
Closing the stream reader seem cleaner to me but dont expect the parser to behave correctly if you cut the flow of data in the middle. Unless you stop after a row delimiter, you're last line will be invalid and incomplete.

**Comment by jhihn** [comment] 2017-12-11 21:01
Right, so how do I keep from reading more of the file than I need to? It seems like there should be a graceful end() or other API call which will turn off parsing and thus the errors after it's been called. Most of the time I'm only looking for at most 1% of the lines in the file.  I guess the alternative is to have some other API to get the lines first then send them to the parser.

**Comment by wdavidw** [comment] 2017-12-11 22:22
Current behavior is correct and shouldn't be changed, possibilites are:
* you listen to the "data" event, get the emited record and disregard error message
* you use options from and to to get a subset of the dataset
* we implement something like a `graceful` option which will disregard any data once end has been called on a source stream writer

**Comment by c0b** [comment] 2017-12-22 07:30
So can this point be implemented?
> we implement something like a graceful option which will disregard any data once end has been called on a source stream writer

I followed from https://stackoverflow.com/a/37682370/5672998 and https://www.bennadel.com/blog/2692-you-have-to-explicitly-end-streams-after-pipes-break-in-node-js.htm to here, am calling this parser.end when in some conditions I want to end reading stream early, however it triggered the similar "Error: Quoted field not terminated at line XXX" I believe this is a false error and this package should handle properly when user explicitly calls `this.end()`

**Comment by wdavidw** [comment] 2017-12-25 22:42
Technically yes, if someone is willing to implement it or if I find the time. The idea is, once `end_gracefully()` is called, no more data will be parsed and the stream won't emit new records.

**Comment by Rob-ModernAnalytics** [comment] 2018-01-15 22:37
Hi,

I have always stopped the parser early by issuing a parser.emit('end') when I'm at the limit of how many rows I want to parse.  This seems to end very gracefully.  Is there a reason why this shouldn't be used for this purpose?

Thanks,

Rob

**Comment by Rob-ModernAnalytics** [comment] 2018-01-15 22:40
One more comment - you also need to set the from: and to: options to the sample you need or the parser will still keep going to the end of the file.

**Comment by wdavidw** [comment] 2019-09-13 21:34
Closing due to lack of activity.

**Closed by wdavidw** 2019-09-13 21:34 UTC
