### ISSUE TITLE
events.js:174       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by habimanaflorbert** [adaltas/node-csv-parse#309] opened 2021-02-14 15:56 UTC
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Invalid Record Length: expect 6, got 1 on line 5
    at Parser.__onRecord (/home/florbert/Documents/nodejs/csv/node_modules/csv-parse/lib/index.js:772:9)
    at Parser.__parse (/home/florbert/Documents/nodejs/csv/node_modules/csv-parse/lib/index.js:660:38)
    at Parser._flush (/home/florbert/Documents/nodejs/csv/node_modules/csv-parse/lib/index.js:478:22)
    at Parser.prefinish (_stream_transform.js:141:10)
    at Parser.emit (events.js:198:13)
    at prefinish (_stream_writable.js:635:14)
    at finishMaybe (_stream_writable.js:643:5)
    at endWritable (_stream_writable.js:663:3)
    at Parser.Writable.end (_stream_writable.js:594:5)
    at ReadStream.onend (_stream_readable.js:672:10)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at Parser.onerror (_stream_readable.js:734:7)
    at Parser.emit (events.js:198:13)
    at done (_stream_transform.js:208:19)
    at _flush (_stream_transform.js:142:7)
    at Parser._flush (/home/florbert/Documents/nodejs/csv/node_modules/csv-parse/lib/index.js:479:5)
    at Parser.prefinish (_stream_transform.js:141:10)
    [... lines matching original stack trace ...]
    at finishMaybe (_stream_writable.js:643:5)

**Additional context**

**Comment by wdavidw** [comment] 2021-02-15 22:38
Sorry but I will close this issue due to a lack a context. It indicates that your CSV input is incorrect, not a bug unless you illustrate one.

**Closed by wdavidw** 2021-02-15 22:38 UTC
Labels: question
